main:
  project_name: predict_rental_price
  experiment_name: development
  steps: all
etl:
  sample: "sample1.csv"
  min_price: 10  # dollars
  max_price: 350  # dollars
data_check:
  kl_threshold: 0.2
modeling:
  # Fraction of data to use for test (the remaining will be used for train and validation)
  test_size: 0.2
  # Fraction of remaining data to use for validation
  val_size: 0.2
  # Fix this for reproducibility, change to have new splits
  random_seed: 42
  # Column to use for stratification (use "none" for no stratification)
  stratify_by: neighbourhood_group
  output_artifact: output_artifact
  # Maximum number of features to consider for the TFIDF applied to the title of the
  # insertion (the column called "name")
  max_tfidf_features: 5
  random_forest:
    n_estimators: 100
    max_depth: 15
    min_samples_split: 4
    min_samples_leaf: 3
    # Here -1 means all available cores
    n_jobs: -1
    criterion: mae
    max_features: 0.5
    oob_score: true